// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUeJ9XEJJiG9N2oSy_YHZrOefduQpcDAg',
    appId: '1:289640275102:web:976d8115c06ce6734aaf8f',
    messagingSenderId: '289640275102',
    projectId: 'pokemonapi-15e18',
    authDomain: 'pokemonapi-15e18.firebaseapp.com',
    storageBucket: 'pokemonapi-15e18.appspot.com',
    measurementId: 'G-JK7CDLCP5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpgyg1CJgjfMCrbiyQFgZKiXs2u4kv4V4',
    appId: '1:289640275102:android:e16376d659d865b34aaf8f',
    messagingSenderId: '289640275102',
    projectId: 'pokemonapi-15e18',
    storageBucket: 'pokemonapi-15e18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUaElLKq8qpETi_28Uqxm0CNeHPAbsU8',
    appId: '1:289640275102:ios:0504622d0b4f25364aaf8f',
    messagingSenderId: '289640275102',
    projectId: 'pokemonapi-15e18',
    storageBucket: 'pokemonapi-15e18.appspot.com',
    iosClientId: '289640275102-ift6p40rm18ipcsqn5e6gp3s94fja12a.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokemon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpUaElLKq8qpETi_28Uqxm0CNeHPAbsU8',
    appId: '1:289640275102:ios:0504622d0b4f25364aaf8f',
    messagingSenderId: '289640275102',
    projectId: 'pokemonapi-15e18',
    storageBucket: 'pokemonapi-15e18.appspot.com',
    iosClientId: '289640275102-ift6p40rm18ipcsqn5e6gp3s94fja12a.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokemon',
  );
}
